# This will dump the server logs and operator logs. Use this mainly for debugging failures.
# Upon cleanup (which happens on molecule test failures), these tasks should run.

- set_fact:
    dump_logs_on_error: "{{ lookup('env', 'MOLECULE_DUMP_LOGS_ON_ERROR') | default('true', True) }}"

- name: Get OSSMPlugin Operator Pod logs
  k8s_log:
    namespace: "{{ ossmplugin.operator_namespace }}"
    label_selectors:
    - app.kubernetes.io/name=ossmplugin-operator
  register: ossmplugin_operator_logs
  ignore_errors: yes
  when:
  - dump_logs_on_error == True

- name: Dump OSSMPlugin Operator Pod logs
  debug:
    msg: "{{ ossmplugin_operator_logs.log_lines }}"
  when:
  - dump_logs_on_error == True
  - ossmplugin_operator_logs is defined and ossmplugin_operator_logs.log_lines is defined

- name: Get OSSMPlugin Pod logs
  k8s_log:
    namespace: "{{ ossmplugin.install_namespace }}"
    label_selectors:
    - app.kubernetes.io/name=ossmplugin
  register: ossmplugin_logs
  ignore_errors: yes
  when:
  - dump_logs_on_error == True

- name: Dump OSSMPlugin Pod logs
  debug:
    msg: "{{ ossmplugin_logs.log_lines }}"
  when:
  - dump_logs_on_error == True
  - ossmplugin_logs is defined and ossmplugin_logs.log_lines is defined
