# This will dump the server logs and operator logs. Use this mainly for debugging failures.
# Upon cleanup (which happens on molecule test failures), these tasks should run.

- set_fact:
    dump_logs_on_error: "{{ lookup('env', 'MOLECULE_DUMP_LOGS_ON_ERROR') | default('true', True) }}"

- name: Get OSSMConsole Operator Pod logs
  k8s_log:
    namespace: "{{ ossmconsole.operator_namespace }}"
    label_selectors:
    - app.kubernetes.io/name=ossmconsole-operator
  register: ossmconsole_operator_logs
  ignore_errors: yes
  when:
  - dump_logs_on_error == True

- name: Dump OSSMConsole Operator Pod logs
  debug:
    msg: "{{ ossmconsole_operator_logs.log_lines }}"
  when:
  - dump_logs_on_error == True
  - ossmconsole_operator_logs is defined and ossmconsole_operator_logs.log_lines is defined

- name: Get OSSMConsole Pod logs
  k8s_log:
    namespace: "{{ ossmconsole.install_namespace }}"
    label_selectors:
    - app.kubernetes.io/name=ossmconsole
  register: ossmconsole_logs
  ignore_errors: yes
  when:
  - dump_logs_on_error == True

- name: Dump OSSMConsole Pod logs
  debug:
    msg: "{{ ossmconsole_logs.log_lines }}"
  when:
  - dump_logs_on_error == True
  - ossmconsole_logs is defined and ossmconsole_logs.log_lines is defined
