template_path: ./apigen-crd.template

source_repositories:
- url: https://github.com/kiali/openshift-servicemesh-plugin
  organization: kiali
  short_name: openshift-servicemesh-plugin
  commit_reference: main
  crd_paths:
  - operator/crd-docs/crd
  cr_paths:
  - operator/crd-docs/cr
  metadata:
    ossmconsoles.kiali.io:
      owner:
      - https://github.com/orgs/kiali/teams/maintainers
