apiVersion: kiali.io/v1alpha1
kind: OSSMPlugin
metadata:
  name: ossmplugin
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  version: "default"

  deployment:
    imageDigest: ""
    imageName: ""
    imagePullPolicy: "IfNotPresent"
    # default: image_pull_secrets is an empty list
    imagePullSecrets: ["image.pull.secret"]
    imageVersion: ""
    namespace: ""

  kiali:
    serviceName: ""
    serviceNamespace: ""
    servicePort: 0
    url: ""
