apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ossmplugins.kiali.io
  labels:
    app: ossmplugin-operator
spec:
  group: kiali.io
  names:
    kind: OSSMPlugin
    listKind: OSSMPluginList
    plural: ossmplugins
    singular: ossmplugin
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
