# These tasks remove all resources such that no remnants of OSSM Console will remain.
#
# Note that we ignore_errors everywhere - we do not want these tasks to ever abort with a failure.
# This is because these are run within a finalizer and if a failure aborts any task here
# the user will never be able to delete the OSSMConsole CR - in fact, the delete will hang indefinitely
# and the user will need to do an ugly hack to fix it.

- ignore_errors: yes
  set_fact:
    k8s_plugin: kubernetes.core.k8s

- name: Get the original CR that was deleted
  ignore_errors: yes
  set_fact:
    current_cr: "{{ _kiali_io_ossmconsole }}"

- name: Print some debug information
  ignore_errors: yes
  vars:
    msg: |
        OSSM Console Variables:
        --------------------------------
        {{ ossmconsole_vars | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"

- name: Set default deployment namespace to the same namespace where the CR lives
  ignore_errors: yes
  set_fact:
    ossmconsole_vars: "{{ ossmconsole_vars | combine({'deployment': {'namespace': current_cr.metadata.namespace}}, recursive=True) }}"
  when:
  - ossmconsole_vars.deployment.namespace is not defined or ossmconsole_vars.deployment.namespace == ""

- name: Disable plugin by ensuring the OSSM Console is removed from the Console list of plugins
  ignore_errors: yes
  vars:
    existing_plugins: "{{ lookup('kubernetes.core.k8s', resource_name='cluster', api_version='operator.openshift.io/v1', kind='Console').spec.plugins | default([]) }}"
  k8s:
    state: patched
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    definition:
      spec:
        plugins: "{{ existing_plugins | difference(['ossmconsole']) }}"

- name: Delete OSSM Console resources
  ignore_errors: yes
  k8s:
    state: absent
    api_version: "{{ k8s_item.apiVersion }}"
    kind: "{{ k8s_item.kind }}"
    namespace: "{{ ossmconsole_vars.deployment.namespace }}"
    name: "{{ k8s_item.metadata.name }}"
  register: delete_result
  until: delete_result.result == {} or (delete_result.result.status is defined and delete_result.result.status == "Success")
  retries: 6
  delay: 10
  when:
  - k8s_item is defined
  - k8s_item.apiVersion is defined
  - k8s_item.kind is defined
  - k8s_item.metadata is defined
  - k8s_item.metadata.name is defined
  with_items:
  - "{{ query(k8s_plugin, namespace=ossmconsole_vars.deployment.namespace, kind='ConfigMap',      resource_name='nginx-config',  api_version='v1') }}"
  - "{{ query(k8s_plugin, namespace=ossmconsole_vars.deployment.namespace, kind='ConfigMap',      resource_name='plugin-config', api_version='v1') }}"
  - "{{ query(k8s_plugin, namespace=ossmconsole_vars.deployment.namespace, kind='Deployment',     resource_name='ossmconsole',    api_version='apps/v1') }}"
  - "{{ query(k8s_plugin, namespace=ossmconsole_vars.deployment.namespace, kind='Service',        resource_name='ossmconsole',    api_version='v1') }}"
  - "{{ query(k8s_plugin, kind='ConsolePlugin', resource_name='ossmconsole', api_version='console.openshift.io/v1alpha1') }}"
  loop_control:
    loop_var: k8s_item
