apiVersion: apps/v1
kind: Deployment
metadata:
  name: ossmplugin
  namespace: {{ ossmplugin_vars.deployment.namespace }}
  labels: {{ ossmplugin_resource_metadata_labels }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ossmplugin
      app.kubernetes.io/instance: ossmplugin
  template:
    metadata:
      name: ossmplugin
      labels: {{ ossmplugin_resource_metadata_labels }}
      annotations:
        ossmplugin.kiali.io/last-updated: "{{ deployment_last_updated }}"
    spec:
{% if ossmplugin_vars.deployment.imagePullSecrets | default([]) | length > 0 %}
      imagePullSecrets:
{% for n in ossmplugin_vars.deployment.imagePullSecrets %}
      - name: {{ n }}
{% endfor %}
{% endif %}
      containers:
      - name: ossmplugin
        image: {{ ossmplugin_vars.deployment.imageName }}{{ '@' + ossmplugin_vars.deployment.imageDigest if ossmplugin_vars.deployment.imageDigest != '' else '' }}:{{ ossmplugin_vars.deployment.imageVersion }}
        imagePullPolicy: {{ ossmplugin_vars.deployment.imagePullPolicy }}
        ports:
        - containerPort: 9443
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: ossmplugin-cert-secret
          readOnly: true
          mountPath: /var/serving-cert
        - name: nginx-conf
          readOnly: true
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: plugin-conf
          readOnly: true
          mountPath: /usr/share/nginx/html/plugin-config.json
          subPath: plugin-config.json
      volumes:
      - name: ossmplugin-cert-secret
        secret:
          secretName: ossmplugin-cert-secret
          defaultMode: 420
      - name: nginx-conf
        configMap:
          name: nginx-conf
          defaultMode: 420
      - name: plugin-conf
        configMap:
          name: plugin-conf
          defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
