---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-ossmplugin
---
apiVersion: kiali.io/v1alpha1
kind: OSSMPlugin
metadata:
  name: ossmplugin
  namespace: dev-ossmplugin
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
  labels:
    kiali.dev: "run-operator-playbook"
spec:

  # Make sure the values below also match those in dev-hosts.yaml

  version: default

  deployment:
    imageVersion: dev

  kiali:
    url: https://kiali-istio-system.apps-crc.testing
