- include_tasks: update-status-progress.yml
  vars:
    status_progress_message: "Creating core resources"

- name: Create OSSM Plugin objects on OpenShift
  include_tasks: process-resource.yml
  vars:
    process_resource_cluster: "openshift"
    role_namespaces: "{{ [ ossmplugin_vars.deployment.namespace ] }}"
  loop:
  - configmap-nginx
  - configmap-plugin
  - deployment
  - service
  - consoleplugin
  loop_control:
    loop_var: process_resource_item
